### ISSUE TITLE
Commands dont seem to work correctly.

### ISSUE THREAD

**Issue by uncreativeCultist** [VALERA771/CustomTeam#1]
When trying to run spawn command, simply tells me how to use command.
In this case, my team name is SerpentsHand.

![image](https://user-images.githubusercontent.com/66176496/228702488-c32ea9cf-36da-44ac-b3fe-f059a71719e3.png)

**Comment by uncreativeCultist** [comment]
if this is some sort of rookie mistake, sorry.

**Comment by VALERA771** [comment]
Should be fixed in 1.2.2
